[project]
name = "solvingtaskwithai"
version = "0.1.0"
description = ""
authors = [
    {name = "arewsa",email = "arewsa5@gmail.com"}
]
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.0.1,<2.0.0",
    "fastapi[standard] (>=0.116.1,<0.117.0)",
    "griffe>=1.14.0",
    "pydantic-extra-types>=2.10.5",
    "geojson-pydantic>=2.0.0",
    "google-genai>=1.39.1",
    "mcp>=1.15.0",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
